export default data = [
  {
    "0": "",
    "1": "",
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "2": "rally logo URL",
    "3": "Sponsor1 URL",
    "4": "Sponsor2URL",
    "5": "Sponsor3 URL",
    "6": "Sponsor4 URL",
    "7": "Sponsor5 URL",
    "8": null,
    "9": null
  },
  {
    "0": "",
    "1": "",
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "2": "sponsor6 URL",
    "3": "sponsor7 URL",
    "4": "Sponsor8 URL",
    "5": "Sponsor9 URL",
    "6": "Sponsor10URL",
    "7": null,
    "8": null,
    "9": null
  },
  {
    "0": "",
    "1": "",
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "2": "",
    "3": "",
    "4": "",
    "5": "",
    "6": "",
    "7": "",
    "8": "Partial Un-official Overall Classification",
    "9": null
  },
  {
    "0": null,
    "1": null,
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "2": null,
    "3": null,
    "4": null,
    "5": null,
    "6": null,
    "7": null,
    "8": null,
    "9": null
  },
  {
    "0": null,
    "1": null,
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "2": null,
    "3": null,
    "4": null,
    "5": null,
    "6": null,
    "7": null,
    "8": null,
    "9": null
  },
  {
    "0": "Pos",
    "1": "Car No",
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "2": "Driver/Co-Driver",
    "3": "Car",
    "4": "Grp",
    "5": "Status",
    "6": "Stages Attempted",
    "7": "Times lost",
    "8": null,
    "9": null
  },
  {
    "0": "",
    "1": "",
    "10": "SSS3",
    "11": "SS4",
    "12": "SS5",
    "13": "SS6",
    "14": "SS7",
    "15": "SS8",
    "16": "Pen",
    "17": "Diff. Leader",
    "18": "Diff Prev",
    "2": "",
    "3": "",
    "4": "",
    "5": "",
    "6": "",
    "7": "Total time",
    "8": "SS1",
    "9": "SSS2"
  },
  {
    "0": "1",
    "1": "48",
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "2": "Ibrahim LUBEGA / Geofrey SERWOGA",
    "3": "Toyota FX",
    "4": "2WD",
    "5": "Active",
    "6": "0",
    "7": "0:00:00:00",
    "8": null,
    "9": null
  },
  {
    "0": "2",
    "1": "40",
    "10": null,
    "11": null,
    "12": null,
    "13": null,
    "14": null,
    "15": null,
    "16": null,
    "17": null,
    "18": null,
    "2": "John Burrows LUMU / Joseph LUTALO Jr.",
    "3": "Subaru Impreza N14",
    "4": "RC2",
    "5": "Active",
    "6": "0",
    "7": "0:00:00:00",
    "8": null,
    "9": null
  }
];
